__author__ = 'jc451634'
temp_file = open('temp.txt','w')
print('First line' ,file=temp_file)
print('Second line' ,file=temp_file)
print('Third line' ,file=temp_file)
print('Fourth line' ,file=temp_file)
temp_file.close()
print('===')
temp_file = open('temp.txt' , 'r')
for line in temp_file:
    line = line.strip()
    print(line)
temp_file.close()
print('===')
temp_file = open('temp.txt', 'r')
my_str = temp_file.read()
print(my_str)
temp_file.close()
print('===')
temp_file = open('temp.txt' , 'r')
lines = temp_file.readlines()
 # print(lines)
for line in lines:
    line = line.strip()
print(line)
temp_file.close()
print('===')
my_list = ['First line\n', 'Second line\n', 'Third line\n', 'Fourth line\n']
out_file = open('out.txt', 'w')
out_file.writelines(my_list)
out_file.close()
